export const APP_CONSTANTS = {
  DEFAULT_TTL_IN_MINUTE: 5,
  CACHE_LRU_SIZE: 5000,
  SAFE_HAVEN_REFRESH_EXPIRY: 38,
  OTP_EXPIRY_IN_MINS: 30,
  SIGN_UP_SESSION_DURATION_IN_MINS: 30,
  COFFER_ID_LENGTH: 10,
  ACCESS_TOKEN_EXPIRATION: '7d',
  REFRESH_TOKEN_EXPIRATION: '90d',
  CLEAN_UP_DURATION_IN_MINS: 360,
  SIGNED_URL_DURATION_IN_MINS: 10,
  RATES_TTL_IN_MINUTE: 3,
  TRANSACTION_EXPIRY_IN_MINUTE: 15,
  WALLET_OVERVIEW_TRANSACTION_LENGTH: 7,
  BANK_LIST_EXPIRY_IN_MINS: 180,
} as const;

export type AppConstants = typeof APP_CONSTANTS;

export const CONSTANTS_TOKEN = 'APP_CONSTANTS';
